name: Download Kernel Source Code

on:
  # push:
  workflow_dispatch:
    inputs:
      tag_or_release:
        description: 'Choose whether to use a Tag or a Release'
        required: false
        default: 'tag' # 默认选择标签
        options:
          - 'tag'
          - 'release'
        type: choice
      release:
        description: "Release"
        required: false
        default: false
        type: string
      tag:
        description: 'v*.*.*'
        required: false
        default: false
        type: string

jobs:
  download:
    permissions:
      contents: write
    name: Download by ${{ github.actor }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      #with:
      #  ref: 
    - name: download source code
      id: code
      run: |
        sudo apt-get update && sudo apt-get upgrade -y && sudo apt-get install repo -y
        cd $GITHUB_WORKSPACE
        mkdir android-kernel && cd android-kernel
        git clone --depth=1 https://android.googlesource.com/kernel/common -b android12-5.10-2024-03
        tar -zcpvf common.tar.gz common
        aria2c https://android.googlesource.com/kernel/common/+archive/refs/heads/android12-5.10-2024-03.tar.gz -o android12-5.10-2024-03.tar.gz
        mkdir ../repo && cd ../repo
        repo init --depth=1 -u https://android.googlesource.com/kernel/manifest -b common-android12-5.10-2024-03 && repo sync
        cd .. && tar -zcpvf repo.tar.gz repo
    - name: upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: android12-5.10-2024-03
        path: |
          ./android-kernel/common.tar.gz
          ./android-kernel/android12-5.10-2024-03.tar.gz
          ./android-kernel/repo.tar.gz
        overwrite: true
    - name: Release
      uses: softprops/action-gh-release@v2
      if: ${{ github.event.inputs.release }} == true
      with:
        tag_name: ${{ github.event.inputs.release }}
        files: |
          ./android-kernel/common.tar.gz
          ./android-kernel/android12-5.10-2024-03.tar.gz
          ./android-kernel/repo.tar.gz
    - name: Release
      uses: softprops/action-gh-release@v2
      if: ${{ github.event.inputs.tag }} == true
      with:
        tag_name: ${{ github.event.inputs.tag }}
        files: |
          ./android-kernel/common.tar.gz
          ./android-kernel/android12-5.10-2024-03.tar.gz
          ./android-kernel/repo.tar.gz
