name: Download Kernel Source Code

on:
  # push:
  workflow_dispatch:
    inputs:
      config:
        description: 'Choose a config.env'
        required: false
        default: 'config.env' # 默认选择标签
        options:
          - 'config.env'
          - 'config.properties.gki_12510'
        type: choice
      tag_or_release:
        description: 'Choose whether to use a Tag or a Release'
        required: false
        default: 'tag' # 默认选择标签
        options:
          - 'tag'
          - 'release'
        type: choice
      tag:
        description: 'v*.*.*'
        required: false
        default: v*.*.*
        type: string
      release:
        description: "release-*"
        required: false
        default: release-*
        type: string

jobs:
  download:
    permissions:
      contents: write
    name: Download by ${{ github.actor }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      #with:
      #  ref: 
    - name: Read the Configuration
      run: |
        CONFIG_ENV=${{ github.event.inputs.config }}
        echo "KERNEL_SOURCE=$(cat $CONFIG_ENV | grep -w "KERNEL_SOURCE" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
        echo "KERNEL_SOURCE_BRANCH=$(cat $CONFIG_ENV | grep -w "KERNEL_SOURCE_BRANCH" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
        echo "KERNEL_CONFIG=$(cat $CONFIG_ENV | grep -w "KERNEL_CONFIG" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV

    - name: Download Source Code
      id: code
      run: |
        sudo apt-get update && sudo apt-get upgrade -y && sudo apt-get install repo -y
        cd $GITHUB_WORKSPACE
        mkdir android-kernel && cd android-kernel
        git clone --depth=1 ${{ env.KERNEL_SOURCE }} -b ${{ env.KERNEL_SOURCE_BRANCH }}
        tar -zcpvf common.tar.gz common
        aria2c ${{ env.KERNEL_SOURCE }}/+archive/refs/heads/${{ env.KERNEL_SOURCE_BRANCH }}.tar.gz -o ${{ env.KERNEL_SOURCE_BRANCH }}.tar.gz
        mkdir ../repo && cd ../repo
        repo init --depth=1 -u https://android.googlesource.com/kernel/manifest -b common-${{ env.KERNEL_SOURCE_BRANCH }} && repo sync
        cd .. && tar -zcpvf repo.tar.gz repo

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.KERNEL_SOURCE_BRANCH }}
        path: |
          ./android-kernel/common.tar.gz
          ./android-kernel/android12-5.10-2024-03.tar.gz
          ./android-kernel/repo.tar.gz
        overwrite: true

    - name: Tag
      if: ${{ github.event.inputs.tag_or_release }} == tag
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ env.KERNEL_SOURCE_BRANCH }}_${{ github.event.inputs.tag }}
        files: |
          ./android-kernel/common.tar.gz
          ./android-kernel/android12-5.10-2024-03.tar.gz
          ./android-kernel/repo.tar.gz

    - name: Release
      if: ${{ github.event.inputs.tag_or_release }} == release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ env.KERNEL_SOURCE_BRANCH }}_-${{ github.event.inputs.release }}
        files: |
          ./android-kernel/common.tar.gz
          ./android-kernel/android12-5.10-2024-03.tar.gz
          ./android-kernel/repo.tar.gz
